### ISSUE TITLE
Tilt Mini and Tilt Regular - Same Color

### ISSUE THREAD

**Issue by adiefender** [avollkopf/cbpi4-BLEHydrom#2]
Where the Tilt website states can see two of the same color if One is Tilt Regular and Tilt Pro mini.

"You can even use a standard Tilt and Tilt Pro Mini together if they are the same color in the Tilt 2 app, so run up to 16 different Tilts at once in the Tilt 2 app with 8 standards and 8 pro minis." - Source: https://tilthydrometer.com/products/tilt-pro-mini-hydrometer-and-thermometer

Please update the plugin to allow the same usage.

**Comment by avollkopf** [comment]
Currently not possible as there is no official information on how to distinguish between Tilt and Tilt pro Mini: https://kvurd.com/blog/tilt-hydrometer-ibeacon-data-format/

Only 8 uuids are shown at the link and no further possibility to differentiate between both types

**Comment by adiefender** [comment]
does this help?

[image: image.png]

**Comment by avollkopf** [comment]
most likely not w/o the attachment :-)

**Comment by adiefender** [comment]
UUID Blue Pro Mini: A495BB60C5B14B44B5121370F02D74DE
UUID Red Pro Mini: A495BB10C5B14B44B5121370F02D74DE

*Daniel Diefenderfer*

**Comment by adiefender** [comment]
I had also reached out to Tilt Themselves and they provided the following
link: https://github.com/frawau/aioblescan

*Daniel Diefenderfer*

**Comment by adiefender** [comment]
Tilt Pro /Mini uses the an SG/minor range from 2000 and above
(theoretically up to 65,535) and standard Tilt uses SG range from 0 to
2000.

You can use this range difference to identify whether a Tilt is a pro or
standard.

**Comment by avollkopf** [comment]
Do you own one of the pro mini versions? if yes, what are the gravity values they report in cbpi4? Question is basically on how to calculate gravity. With the  old ones, you divide 'minor' by 1000

Mini: (minor-1000)/1000 ????

**Comment by adiefender** [comment]
i have two of them. The Blue PRo mini in TiltPi config shows gravity as
1.0074
In CBPi4 as 101

*Daniel Diefenderfer*

**Comment by avollkopf** [comment]
Please run cbpi with debug log level @ 20

-> add this to config.yaml: debug-log-level: 20

and restart cbpi service.

The plugin should log the original values from the tilt:
logging.info("Tilt data received: Temp: %s Gravity: %s RSSI: %s" % (beacon['major'], beacon['minor'], beacon['rssi']))
(This line is already included in the plugin)

-> Post the output, once it's in your log

**Comment by adiefender** [comment]
with the log lvl set to 20, rebooted, and retrieved the logs from the
webgui, the following shows in the CBPI4.log.
"Tilt data received: Temp: 694 Gravity: 10077 RSSI: -65"

when I'm on the CLI and go to the log dir and open
the  sensor_WoK3Scq6DnJWvcaVAbaD6c.log

2024-07-11 13:16:48,10.079
2024-07-11 13:16:52,10.081
2024-07-11 13:16:56,10.078
2024-07-11 13:17:00,10.076
2024-07-11 13:17:04,10.079
2024-07-11 13:17:08,10.079
2024-07-11 13:17:16,10.08
2024-07-11 13:17:22,10.079
2024-07-11 13:17:26,10.079

Is there a separate log to look at?

*Daniel Diefenderfer*

**Comment by avollkopf** [comment]
I was referring t the cbpi logfile where you can see the error, info,... logs. anyhow, this is also good. Seems to be that the Tilt pro mini is reporting values like 10077...  which i need to divide by 10000 instead of 1000. Temp values seem to be also multiplied with 10. What was your actual temp reading in the app?

Kind of weird, but seems to be possible to adapt. Give me some time

**Comment by avollkopf** [comment]
@adiefender try the dev repo and select your device in the sensor hardware settings:
![image](https://github.com/user-attachments/assets/6a0478fe-9253-40f7-b4ea-4eecbef2d40a)

I am not sure, if the calculations for the tilt mini pro are already correct. 

My assumption is now: Temp must be divided by 10 and 9000 must be subtracted from the gravity.

EDIT: Gravity is probably more the reported value divided by 10000. Please test and report back (changed in the dev branch)

**Comment by adiefender** [comment]
![image](https://github.com/user-attachments/assets/a3664dbe-f25b-4ed6-953e-3303df75332b)
Looks Good, I can do the calibration as it is only off by .0003 from what TiltPi Shows. 
Temp is spot on!

Since the adjustment is for Tilt Pro and it's use of a larger base number for sensor data, might want to call the Dropdown Tilt Pro/Pro mini.

**Comment by avollkopf** [comment]
ok, will adapt that, but you will need to change it once it's updated. Is the temp reading also working?

**Comment by adiefender** [comment]
Temp is reading correctly. I will be getting another ferment going and checking the extended digits to see how they track during active fermentation.

**Comment by avollkopf** [comment]
Updated dev branch. 

1 Hardware Selection as proposed
2. increases gravity reading digits to 4

**Comment by avollkopf** [comment]
merged development to main branch
